"""Drosophila PD FlyGym computational research package."""

from importlib.metadata import PackageNotFoundError, version


try:
    __version__ = version("drosophila-pd-flygym")
except PackageNotFoundError:  # Source checkouts before editable installation.
    __version__ = "0+unknown"

from .automation import (  # noqa: E402
    ArtifactManager,
    BenchmarkCenter,
    DatasetCatalog,
    DatasetCatalogEntry,
    DeveloperToolkit,
    ExperimentQueueManager,
    ProjectHealthMonitor,
    PublicationBuilder,
    ReproducibilityCenter,
    ResearchAutomationPlatform,
)
from .digital_twin_platform import (  # noqa: E402
    CollaborationLayer,
    DigitalTwinManager,
    DigitalTwinPlatform,
    DigitalTwinRecord,
    KnowledgeGraph,
    ScenarioRecord,
    ScenarioWorkspace,
    StateDiff,
    StateDiffEngine,
    TemporalExplorer,
    TwinAnnotation,
    VirtualLaboratorySession,
)
from .research_campaign import (  # noqa: E402
    CampaignEvent as ResearchCampaignEvent,
    CampaignHistory as ResearchCampaignHistory,
    CampaignManager as ResearchCampaignManager,
    CampaignManifest as ResearchCampaignManifest,
    CampaignState as ResearchCampaignState,
    ExperimentSpec as ResearchExperimentSpec,
)
from .research_pipeline import (  # noqa: E402
    DatasetInput as StudyDatasetInput,
    StudyOrchestrator,
    StudyRequest,
    StudyResult,
    run_study,
)
from .research_execution import (  # noqa: E402
    ArtifactRegistry as ExecutionArtifactRegistry,
    DatasetDiscovery,
    ExecutionContext,
    ExecutionHistory,
    ExecutionResult,
    ExecutionRuntime,
    ExecutionState,
)
from .dataset_adapter import (  # noqa: E402
    DatasetDiscoveryReport,
    DatasetMetadata,
    DatasetValidationReport,
    DatasetValidator,
    FlyGymDataset,
    RolloutFile,
    RolloutLocator,
    discover_datasets,
)
from .experiment_runtime import (  # noqa: E402
    EventLog,
    ExperimentContext,
    ExperimentEvent,
    ExperimentEventType,
    ExperimentOutputs,
    ExperimentRuntime,
    ExperimentSession,
    ExperimentSummary,
    OutputPaths,
    SessionState,
)
from .research_kernel import (  # noqa: E402
    KernelContext,
    KernelEvent,
    KernelEventType,
    KernelState,
    ResearchBus,
    ResearchKernel,
    ResourceManager,
    ResourceRecord,
    ServiceRecord,
    ServiceRegistry,
    TaskResult,
    TaskScheduler,
    TaskSpec,
)
from .flygym_adapter import (  # noqa: E402
    FlyBuilder,
    FlyConfig,
    FlyGymAdapter,
    FlyGymConfig,
    FlyGymRuntime,
    FlyGymUnavailableError,
    ObservationFrame,
    RolloutData,
    RolloutRecorder,
    RuntimeState,
    SimulationBuilder,
    WorldBuilder,
    export_rollout,
)
from .viewer_export import (  # noqa: E402
    PoseExportResult,
    PoseValidationError,
    ValidationReport,
    export_viewer_pose,
    validate_pose_document,
)
from .research_assistant import (  # noqa: E402
    AssistantReport,
    ResearchAssistant,
)

__all__ = [
    "__version__",
    "ArtifactManager",
    "BenchmarkCenter",
    "DatasetCatalog",
    "DatasetCatalogEntry",
    "DeveloperToolkit",
    "ExperimentQueueManager",
    "ProjectHealthMonitor",
    "PublicationBuilder",
    "ReproducibilityCenter",
    "ResearchAutomationPlatform",
    "CollaborationLayer",
    "DigitalTwinManager",
    "DigitalTwinPlatform",
    "DigitalTwinRecord",
    "KnowledgeGraph",
    "ScenarioRecord",
    "ScenarioWorkspace",
    "StateDiff",
    "StateDiffEngine",
    "TemporalExplorer",
    "TwinAnnotation",
    "VirtualLaboratorySession",
    "ResearchCampaignEvent",
    "ResearchCampaignHistory",
    "ResearchCampaignManager",
    "ResearchCampaignManifest",
    "ResearchCampaignState",
    "ResearchExperimentSpec",
    "StudyDatasetInput",
    "StudyOrchestrator",
    "StudyRequest",
    "StudyResult",
    "run_study",
    "ExecutionArtifactRegistry",
    "DatasetDiscovery",
    "ExecutionContext",
    "ExecutionHistory",
    "ExecutionResult",
    "ExecutionRuntime",
    "ExecutionState",
    "DatasetDiscoveryReport",
    "DatasetMetadata",
    "DatasetValidationReport",
    "DatasetValidator",
    "FlyGymDataset",
    "RolloutFile",
    "RolloutLocator",
    "discover_datasets",
    "EventLog",
    "ExperimentContext",
    "ExperimentEvent",
    "ExperimentEventType",
    "ExperimentOutputs",
    "ExperimentRuntime",
    "ExperimentSession",
    "ExperimentSummary",
    "OutputPaths",
    "SessionState",
    "KernelContext",
    "KernelEvent",
    "KernelEventType",
    "KernelState",
    "ResearchBus",
    "ResearchKernel",
    "ResourceManager",
    "ResourceRecord",
    "ServiceRecord",
    "ServiceRegistry",
    "TaskResult",
    "TaskScheduler",
    "TaskSpec",
    "FlyBuilder",
    "FlyConfig",
    "FlyGymAdapter",
    "FlyGymConfig",
    "FlyGymRuntime",
    "FlyGymUnavailableError",
    "ObservationFrame",
    "RolloutData",
    "RolloutRecorder",
    "RuntimeState",
    "SimulationBuilder",
    "WorldBuilder",
    "export_rollout",
    "PoseExportResult",
    "PoseValidationError",
    "ValidationReport",
    "export_viewer_pose",
    "validate_pose_document",
    "AssistantReport",
    "ResearchAssistant",
]
