"""Release-candidate integration report for the existing v1/v2 platform.

The builder inventories existing software and documentation. It does not run
FlyGym, MuJoCo, simulations, or scientific evidence generation.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

from .benchmarking import BENCHMARK_STAGES
from .developer_tooling import ArchitectureSnapshot
from .project_health import ProjectHealth
from .release_engineering import ReleaseManifest, ReleaseNotesGenerator


@dataclass(frozen=True)
class ReleaseCandidateConfig:
    version: str = "v1.0.0-rc"
    output_dir: str = "docs/release_candidate"


class ReleaseCandidateBuilder:
    """Compose release/readiness reports from existing static tooling."""

    def __init__(self, root: str | Path, config: ReleaseCandidateConfig | None = None) -> None:
        self.root = Path(root).resolve()
        self.config = config or ReleaseCandidateConfig()

    def build(self) -> dict[str, Any]:
        health = ProjectHealth(self.root).run()
        architecture = ArchitectureSnapshot(self.root).build()
        release = ReleaseManifest(self.root, version=self.config.version).build(
            health={"overall_pass": health["overall_pass"], "summary": health["summary"]}
        )
        release.update({
            "release_candidate": True,
            "architecture": {
                "module_count": len(architecture["modules"]),
                "api_module_count": architecture["api"]["module_count"],
                "dependency_edge_count": len(architecture["dependencies"]["edges"]),
                "plugin_hook_count": len(architecture["hooks"]["hooks"]),
                "plugin_capability_count": len(architecture["hooks"]["capabilities"]),
            },
            "module_index": architecture["modules"],
            "api_index": architecture["api"],
            "dependency_graph": architecture["dependencies"],
            "plugin_registry": architecture["hooks"],
            "validation_summary": {
                "status": "static_and_contract_checks_only",
                "scientific_validation_input_required": True,
                "simulation_executed": False,
                "evidence_modified": False,
                "scope": "Software integration and release readiness only.",
            },
            "coverage_report": {
                "status": "not_measured",
                "reason": "Coverage tooling is not part of the release builder; pytest remains the regression gate.",
            },
            "performance_report": {
                "status": "caller_supplied_only",
                "stages": list(BENCHMARK_STAGES),
                "simulation_executed": False,
            },
            "known_limitations": [
                "FlyGym/MuJoCo integration still requires the documented Colab environment.",
                "Scientific validation reports require caller-supplied real rollout/reference data.",
                "PDF architecture output is not generated by this dependency-minimal builder.",
            ],
            "scientific_boundary": (
                "Integration/release readiness only. No new scientific result, biological validation, "
                "clinical claim, or simulation output is generated."
            ),
        })
        return release

    def write(self, output_dir: str | Path | None = None) -> dict[str, Any]:
        output = Path(output_dir or self.config.output_dir)
        if not output.is_absolute():
            output = self.root / output
        output.mkdir(parents=True, exist_ok=True)
        report = self.build()
        generator = ReleaseNotesGenerator()
        (output / "release.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        (output / "release.md").write_text(generator.to_markdown(report).rstrip() + "\n", encoding="utf-8")
        (output / "release.html").write_text(generator.to_html(report), encoding="utf-8")
        self._write_json(output / "module_index.json", report["module_index"])
        self._write_json(output / "api_index.json", report["api_index"])
        self._write_json(output / "dependency_graph.json", report["dependency_graph"])
        (output / "dependency_graph.dot").write_text(_dependency_dot(report["dependency_graph"]), encoding="utf-8")
        self._write_json(output / "plugin_registry.json", report["plugin_registry"])
        self._write_json(output / "health_report.json", ProjectHealth(self.root).run())
        self._write_json(output / "validation_summary.json", report["validation_summary"])
        self._write_json(output / "coverage_report.json", report["coverage_report"])
        self._write_json(output / "performance_report.json", report["performance_report"])
        (output / "architecture.pdf.note").write_text(
            "PDF architecture output is not generated by the dependency-minimal release builder. See release.md and dependency_graph.dot.\n",
            encoding="utf-8",
        )
        manifest = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "version": self.config.version,
            "files": sorted(path.name for path in output.iterdir() if path.is_file()),
            "scientific_boundary": report["scientific_boundary"],
        }
        self._write_json(output / "artifact_manifest.json", manifest)
        return report

    @staticmethod
    def _write_json(path: Path, payload: Any) -> None:
        path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _dependency_dot(graph: Mapping[str, Any]) -> str:
    lines = ["digraph fly_studio_release_candidate {"]
    lines.extend(f'  "{node}";' for node in graph.get("nodes", []))
    lines.extend(f'  "{edge["source"]}" -> "{edge["resolved"]}";' for edge in graph.get("edges", []) if edge.get("resolved"))
    lines.append("}")
    return "\n".join(lines) + "\n"


__all__ = ["ReleaseCandidateBuilder", "ReleaseCandidateConfig"]
