/** Report/publication bridge backed by the existing laboratory report stores. */
export class ReportBridge {
    constructor({ laboratory, reportGenerator }) {
        this.laboratory = laboratory;
        this.reportGenerator = reportGenerator;
    }

    renderReports(container) {
        const reports = this.laboratory?.reports?.list?.() ?? [];
        container.append(this.heading('Report center', `${reports.length} report${reports.length === 1 ? '' : 's'}`));
        if (!reports.length) {
            container.append(this.note('No generated report is attached to the current workspace.'));
            return;
        }
        reports.forEach((report) => container.append(this.row(report.format, report.createdAt ?? '')));
    }

    renderPublication(container) {
        const dashboard = this.laboratory?.dashboard?.() ?? {};
        container.append(this.heading('Publication center', 'Existing reports and exports only'));
        container.append(this.note(`${dashboard.reports ?? 0} report(s) and ${dashboard.exports ?? 0} export(s) are available.`));
        container.append(this.note('No publication claim or scientific conclusion is generated by the browser.'));
    }

    heading(title, subtitle) {
        const element = document.createElement('div');
        element.className = 'laboratory-section-heading';
        const titleElement = document.createElement('h3');
        titleElement.textContent = title;
        const subtitleElement = document.createElement('small');
        subtitleElement.textContent = subtitle;
        element.append(titleElement, subtitleElement);
        return element;
    }

    row(title, detail) {
        const element = document.createElement('div');
        element.className = 'laboratory-list-row';
        element.textContent = `${title} | ${detail}`;
        return element;
    }

    note(text) {
        const element = document.createElement('p');
        element.className = 'muted laboratory-note';
        element.textContent = text;
        return element;
    }
}
